# Generated by Django 2.2.6 on 2022-08-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
